#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Plan Generator - Create structured action plans for AI Employee tasks.

Generates Plan.md files with step-by-step checklists for the AI to follow.

Usage:
    python plan_generator.py /path/to/vault --task "Task description"
"""

import sys
import argparse
from pathlib import Path
from datetime import datetime
from typing import Optional, List, Dict, Any


class PlanGenerator:
    """Generate action plans for tasks."""
    
    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.plans_folder = self.vault_path / 'Plans'
        self.needs_action = self.vault_path / 'Needs_Action'
        
        self.plans_folder.mkdir(parents=True, exist_ok=True)
    
    def generate_plan(self, 
                      task_description: str,
                      task_type: str = 'general',
                      priority: str = 'normal',
                      from_file: Optional[Path] = None) -> Path:
        """
        Generate a plan for a task.
        
        Args:
            task_description: Description of the task
            task_type: Type of task (email, file, whatsapp, etc.)
            priority: Task priority (low, normal, high, critical)
            from_file: Optional source file
            
        Returns:
            Path to created plan file
        """
        # Generate plan ID
        plan_id = f"PLAN_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        # Generate suggested steps based on task type
        steps = self._generate_steps(task_type, task_description)
        
        # Create plan content
        content = f'''---
type: plan
created: {datetime.now().isoformat()}
status: in_progress
task_id: {plan_id}
priority: {priority}
task_type: {task_type}
estimated_steps: {len(steps)}
---

# Plan: {task_description[:50]}

## Objective

{task_description}

## Steps

{self._format_steps(steps)}

## Resources

- [[Company_Handbook]] - Rules of engagement
- [[Business_Goals]] - Current objectives
{f"- [[{from_file.stem}]] - Source file" if from_file else ""}

## Approval Required

Check if any steps require human approval:
{self._check_approvals(task_type)}

## Notes

*Add additional notes during execution*

---
*Generated by Plan Generator*
'''
        
        # Create file
        safe_name = self._sanitize_filename(task_description[:30])
        filepath = self.plans_folder / f'{plan_id}_{safe_name}.md'
        filepath.write_text(content, encoding='utf-8')
        
        return filepath
    
    def _generate_steps(self, task_type: str, description: str) -> List[str]:
        """Generate suggested steps based on task type."""
        
        common_steps = [
            "Read and understand the task requirements",
            "Check Company Handbook for relevant rules"
        ]
        
        type_specific_steps = {
            'email': [
                "Identify sender and check if known contact",
                "Determine required response",
                "Draft response (if needed)",
                "Request approval if sending to new contact",
                "Send email or archive",
                "Update Dashboard with completion"
            ],
            'whatsapp': [
                "Identify sender and urgency level",
                "Determine required action",
                "Draft response",
                "Request approval if needed",
                "Send response via WhatsApp",
                "Mark as done"
            ],
            'file': [
                "Identify file type and content",
                "Determine required processing",
                "Extract actionable items",
                "Process or route appropriately",
                "Archive or delete original"
            ],
            'invoice': [
                "Identify client and amount",
                "Check if invoice exists",
                "Generate invoice if needed",
                "Create approval request",
                "Send invoice after approval",
                "Log transaction"
            ],
            'payment': [
                "Verify payment details",
                "Check approval thresholds",
                "Create approval request (always required)",
                "Process payment after approval",
                "Log transaction",
                "Update accounting records"
            ],
            'general': [
                "Analyze task requirements",
                "Identify required resources",
                "Execute task steps",
                "Request approval if needed",
                "Complete and document",
                "Move to Done folder"
            ]
        }
        
        return common_steps + type_specific_steps.get(task_type, type_specific_steps['general'])
    
    def _format_steps(self, steps: List[str]) -> str:
        """Format steps as markdown checklist."""
        return '\n'.join([f'- [ ] {step}' for step in steps])
    
    def _check_approvals(self, task_type: str) -> str:
        """Check if task type requires approval."""
        
        approval_checks = {
            'email': '- [ ] Sending to new contact → Requires approval',
            'whatsapp': '- [ ] Response to unknown number → Requires approval',
            'payment': '- [ ] ALL payments → Requires approval',
            'invoice': '- [ ] Sending invoice → Requires approval',
            'file': '- [ ] Deleting files → May require approval',
            'general': '- [ ] Review task for approval requirements'
        }
        
        return approval_checks.get(task_type, approval_checks['general'])
    
    def _sanitize_filename(self, text: str) -> str:
        """Sanitize text for filename."""
        invalid = '<>:"/\\|？*'
        for char in invalid:
            text = text.replace(char, '_')
        return text.strip()
    
    def create_plan_from_action_file(self, action_file: Path) -> Optional[Path]:
        """Create a plan from an existing action file."""
        if not action_file.exists():
            return None
        
        content = action_file.read_text(encoding='utf-8')
        
        # Extract type from frontmatter
        task_type = 'general'
        for line in content.split('\n')[:20]:
            if line.startswith('type:'):
                task_type = line.split(':')[1].strip()
                break
        
        # Extract subject/description
        description = f"Process {task_type} from {action_file.name}"
        for line in content.split('\n'):
            if line.startswith('subject:'):
                description = line.split(':')[1].strip()
                break
            if line.startswith('from:'):
                description = f"Process {task_type} from {line.split(':')[1].strip()}"
                break
        
        return self.generate_plan(
            task_description=description,
            task_type=task_type,
            from_file=action_file
        )


def main():
    parser = argparse.ArgumentParser(description='Plan Generator')
    parser.add_argument('vault_path', help='Path to Obsidian vault')
    parser.add_argument('--task', help='Task description')
    parser.add_argument('--type', default='general', help='Task type')
    parser.add_argument('--priority', default='normal', choices=['low', 'normal', 'high', 'critical'])
    parser.add_argument('--from-file', help='Create plan from action file')
    
    args = parser.parse_args()
    
    generator = PlanGenerator(args.vault_path)
    
    if args.from_file:
        action_file = Path(args.from_file)
        if not action_file.exists():
            print(f"Error: File not found: {action_file}")
            sys.exit(1)
        
        plan_path = generator.create_plan_from_action_file(action_file)
        print(f"Plan created: {plan_path}")
    elif args.task:
        plan_path = generator.generate_plan(
            task_description=args.task,
            task_type=args.type,
            priority=args.priority
        )
        print(f"Plan created: {plan_path}")
    else:
        print("Error: Specify --task or --from-file")
        sys.exit(1)


if __name__ == '__main__':
    main()
